language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
script: coverage run --source lib setup.py test
sudo: false
cache: pip

after_success: 
  - coveralls
  - codecov
